#!/usr/bin/env python3
"""
clinic-triage / triage.py
-------------------------
Stage 2 of the taildrop -> sardinetracker chain. Reads PDFs out of the Taildrop
inbox, decides which are clinical records, and proposes a description for each.

    ./triage.py                     triage the inbox, ask qwen for descriptions
    ./triage.py --dry-run           classify and extract only; never call a model
    ./triage.py --report            show what is sitting in the queue
    ./triage.py --force             re-triage files the manifest has already seen
    ./triage.py --inbox ~/somewhere

Nothing is uploaded and nothing is written to the record. Every document ends up
as a proposal in queue/ for you to read before stage 3 posts it. A proposal
records where each field came from - regex, letterhead, or the model - so a
wrong field can be traced to the thing that produced it.

Only stdlib. Requires `pdftotext` (poppler) and, unless --dry-run, `ollama serve`.
"""

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone

HOST = "http://127.0.0.1:11434"
MODEL = "qwen-local"
THINK = False          # bridge.py measured qwen3 thinking at ~1.7x slower, no gain
NUM_CTX = 8192
NUM_PREDICT = 400      # the JSON we want back is short; cap the slow half
MODEL_CHARS = 6000     # how much document text the model ever sees

HERE = os.path.dirname(os.path.abspath(__file__))
STATE_DIR = os.path.join(HERE, "state")
QUEUE_DIR = os.path.join(HERE, "queue")
MANIFEST = os.path.join(STATE_DIR, "manifest.json")
DEFAULT_INBOX = os.path.expanduser("~/Downloads/taildrop")


def _known_names():
    """Patient names to scrub from model output, from config.json."""
    path = os.path.join(HERE, "config.json")
    try:
        with open(path) as f:
            return tuple(json.load(f).get("patient_names") or ())
    except (OSError, ValueError):
        return ()


KNOWN_NAMES = _known_names()
ROSTER = []          # populated in main() from state/clinicians.json


# ============================================================
# Gate 1 - is this a clinical record at all?
# ============================================================
# Tuned against 69 real PDFs out of the Taildrop inbox, which is a much harder
# problem than it first looks. The folder holds journal articles about lupus,
# legal drafts, patient-education leaflets, this tracker's own PDF exports and
# work documents from the plant - all of them full of clinical vocabulary. A
# keyword score cannot separate those from actual records; on the first pass it
# passed 62 of 63, including a file containing nothing but an account recovery
# code.
#
# So the test is structural, not lexical. A record generated by a provider about
# a specific patient carries a demographics block (a name field plus a date of
# birth or MRN) or an encounter structure. A paper about anti-dsDNA isotypes
# carries neither, however much clinical language it contains.

MIN_CHARS = 400        # below this there is nothing to classify or describe

ANCHORS = {
    "patient_block": r"patient\s+name|patient\s*:|\bMRN\b|"
                     r"medical\s+record\s+(?:number|#)|patient\s+id|account\s*#",
    "dob_field":     r"\bDOB\b|date\s+of\s+birth",
    "encounter":     r"date\s+of\s+service|encounter\s+date|admission|discharge|"
                     r"visit\s+summary|chief\s+complaint|vitals?\b|"
                     r"collected\s+date|accession",
}

# (pattern, count at which the document is disqualified). Thresholds are set
# from the measured corpus: real records do touch these words, just rarely.
# Journal articles run 6-80 hits; a visit summary that happens to say
# "abstract" once does not.
VETOES = {
    "journal_article": (r"\bdoi\b|doi\.org|pubmed|\bet\s+al\.|\babstract\b|"
                        r"\bkeywords\b|\u00a9|\bvol\.\s*\d|peer.reviewed", 5),
    "own_report":      (r"biotracking|sardinetracker|flare\s+score|generated\s+by", 2),
    "legal_filing":    (r"\bplaintiff\b|\bdefendant\b|\bcomplaint\b|\bhereby\b|"
                        r"\bexhibit\b|\bC\.?F\.?R\.?\b|\baffidavit\b|"
                        r"\bcounsel\b|respectfully\s+submit", 5),
    "insurance_admin": (r"enrollment|premium|subscriber|member\s+id|deductible|"
                        r"policy\s+number|coverage", 10),
    "work_document":   (r"incident\s+number|work\s+order|site\s+name|"
                        r"down\s*(?:time|hrs)|equipment\s+status|\bMTSC\b", 2),
}


def classify(text):
    """Return (verdict, detail).

    clinical      - carries a demographics block or an encounter structure
    not_clinical  - tripped a veto, or carries no record structure at all
    ambiguous     - partial structure; described anyway, but flagged for a read
    too_short     - not enough text to judge
    """
    anchors = {k: len(re.findall(v, text, re.I | re.M))
               for k, v in ANCHORS.items()}
    vetoes = {k: len(re.findall(pat, text, re.I | re.M))
              for k, (pat, _) in VETOES.items()}
    tripped = [k for k, (_, limit) in VETOES.items() if vetoes[k] >= limit]

    detail = {"chars": len(text), "anchors": anchors, "vetoes": vetoes,
              "tripped": tripped}

    if len(text) < MIN_CHARS:
        detail["reason"] = f"only {len(text)} characters of text"
        return "too_short", detail

    if tripped:
        detail["reason"] = "looks like " + ", ".join(
            t.replace("_", " ") for t in tripped)
        return "not_clinical", detail

    identified = anchors["patient_block"] >= 1 and anchors["dob_field"] >= 1
    encounter = anchors["encounter"] >= 3
    if identified or encounter:
        detail["reason"] = ("patient demographics block" if identified
                            else "encounter structure")
        return "clinical", detail

    if anchors["patient_block"] or anchors["encounter"]:
        detail["reason"] = "partial record structure only"
        return "ambiguous", detail

    detail["reason"] = "no patient or encounter structure"
    return "not_clinical", detail


# ============================================================
# Gate 2 - deterministic fields
# ============================================================
# Anything readable off the page is read off the page; the model is only asked
# for what needs judgement. Every rule here was written against a real failure
# in the inbox, not imagined in advance.

DATE_RX = (r"(\d{1,2}/\d{1,2}/\d{4}|\d{4}-\d{2}-\d{2}"
           r"|[A-Z][a-z]{2,8}\s+\d{1,2},\s*\d{4}|\d{1,2}-[A-Z][a-z]{2}-\d{4})")

DATE_LABELS = [
    (10, r"collected\s*(?:date\s*/?\s*time)?"),
    (9,  r"date\s+of\s+service"),
    (8,  r"(?:service|visit|encounter|exam)\s+date"),
    (8,  r"visit\s+note\s*[-–]"),
    (7,  r"received\s*(?:date\s*/?\s*time)?"),
    (5,  r"(?:report|result)(?:ed)?\s+date"),
    (4,  r"electronically\s+signed\s+by"),
    (3,  r"date\s+printed"),
]

BIRTH_RX = re.compile(r"\bDOB\b|date\s+of\s+birth|birth\s*date", re.I)

# Nothing in this record predates the tracker's subject matter by decades. A
# date below this is a birthday, a form's printed example, or a copyright year.
EARLIEST_PLAUSIBLE = "2000-01-01"


def parse_date(raw):
    """Normalise one date string to YYYY-MM-DD, or None."""
    raw = raw.strip()
    for fmt in ("%m/%d/%Y", "%Y-%m-%d", "%B %d, %Y", "%b %d, %Y", "%d-%b-%Y"):
        try:
            return datetime.strptime(raw, fmt).date().isoformat()
        except ValueError:
            continue
    return None


def find_birth_dates(text):
    """Every date that looks like a date of birth, to be excluded everywhere.

    Two traps, both seen in this inbox:

    The label and its value are routinely on different lines - a visit note puts
    'DOB:' in a header row and '01/02/1980' in the row beneath. Looking only at
    the labelled line misses it, and the birthday then wins any 'earliest date'
    fallback.

    But that header row also reads 'Visit Note - March 4, 2026 ... DOB:',
    so blindly harvesting every date near the label blacklists the document's
    own date. Only dates *after* the label count, and the following lines are
    consulted only when the label's own line carries no date after it.
    """
    lines = text.splitlines()
    found = set()
    for i, line in enumerate(lines):
        m = BIRTH_RX.search(line)
        if not m:
            continue
        # Only the FIRST date after the label. A lab header reads
        # "DOB: 01/02/1980  Age: 36  Specimen: ...  Collected: 03/04/2026" -
        # taking every date after the label blacklists the collection date too,
        # and the document then has no date at all.
        after = line[m.end():]
        first = re.search(DATE_RX, after)
        if first:
            iso = parse_date(first.group(1))
            if iso:
                found.add(iso)
            continue
        for probe in lines[i + 1:i + 3]:      # value wrapped to the next row
            nxt = re.search(DATE_RX, probe)
            if nxt:
                iso = parse_date(nxt.group(1))
                if iso:
                    found.add(iso)
                break
    return found


FILENAME_DATE_PATTERNS = [
    # 2025.12.05 / 2026-01-20 / 2025_12_05
    (r"(20\d{2})[._-](\d{1,2})[._-](\d{1,2})", ("y", "m", "d")),
    # 04-01-2026 / 1.3.26 / 11_11_2025 / 9-2-2026
    (r"(\d{1,2})[._-](\d{1,2})[._-](20\d{2}|\d{2})", ("m", "d", "y")),
    # 20260219, no separators
    (r"(20\d{2})(\d{2})(\d{2})(?!\d)", ("y", "m", "d")),
    # 05112026 / 10012025, no separators
    (r"(?<!\d)(\d{2})(\d{2})(20\d{2})(?!\d)", ("m", "d", "y")),
]

# "Jan 15, 2026" / "Jan_15,_2026"
FILENAME_MONTH_RX = re.compile(
    r"([A-Z][a-z]{2,8})[_\s]+(\d{1,2}),?[_\s]*(20\d{2})")


def date_from_filename(name):
    """A date out of the filename. In this inbox that is the single most
    reliable signal available - the files are named by date of service."""
    stem = os.path.splitext(os.path.basename(name))[0]
    m = FILENAME_MONTH_RX.search(stem)
    if m:
        for fmt in ("%B %d %Y", "%b %d %Y"):
            try:
                return datetime.strptime(
                    f"{m.group(1)} {m.group(2)} {m.group(3)}", fmt).date().isoformat()
            except ValueError:
                continue
    for pattern, order in FILENAME_DATE_PATTERNS:
        for m in re.finditer(pattern, stem):
            parts = dict(zip(order, m.groups()))
            y, mo, d = parts["y"], int(parts["m"]), int(parts["d"])
            y = int(y) if len(y) == 4 else 2000 + int(y)
            if not (1 <= mo <= 12 and 1 <= d <= 31 and 2000 <= y <= 2099):
                continue
            try:
                return datetime(y, mo, d).date().isoformat()
            except ValueError:
                continue
    return None


def _date_appears_in(iso, text):
    """Does this date actually occur in the document, in any usual rendering?

    A filename is normally the best signal in this inbox, but not an infallible
    one: two copies of the same ER note arrived as ER-2025-03-04.pdf and
    2026-03-04-ER-pleurisy.pdf, with identical text whose own dates read
    03/4/2026. One filename is simply wrong by a year. When the filename's date
    is nowhere in the document, say so rather than filing it quietly.
    """
    d = datetime.strptime(iso, "%Y-%m-%d").date()
    renderings = {
        f"{d.month}/{d.day}/{d.year}", f"{d.month:02d}/{d.day:02d}/{d.year}",
        iso, d.strftime("%B %-d, %Y"), d.strftime("%b %-d, %Y"),
        d.strftime("%d-%b-%Y"),
    }
    return any(r in text for r in renderings)


def extract_date(text, filename=None):
    """Best document date. Labelled beats the filename; the filename beats a
    guess. There is deliberately no 'earliest date in the document' fallback -
    it was wrong far more often than it was right."""
    birthdays = find_birth_dates(text)
    today = datetime.now().date().isoformat()

    def usable(iso):
        return iso and iso not in birthdays and EARLIEST_PLAUSIBLE <= iso <= today

    best = None
    for line in text.splitlines():
        for weight, label in DATE_LABELS:
            m = re.search(label + r"\s*:?\s*" + DATE_RX, line, re.I)
            if m:
                iso = parse_date(m.group(1))
                if usable(iso) and (best is None or weight > best[0]):
                    best = (weight, iso, label)
    if best:
        return best[1], f"labelled date ({best[2]})"

    if filename:
        iso = date_from_filename(filename)
        if usable(iso):
            return iso, ("filename" if _date_appears_in(iso, text)
                         else "filename (NOT corroborated in the document)")

    return None, None


PROVIDER_LABELS = [
    r"electronically\s+signed\s+by", r"ordering\s+provider",
    r"attending(?:\s+physician)?", r"referring\s+(?:provider|physician)",
    r"\bprovider\b", r"physician",
]

CREDENTIAL_RX = re.compile(
    r"\b(?:M\.?D\.?|D\.?O\.?|N\.?P\.?|P\.?A\.?-?C?|R\.?N\.?|Ph\.?D\.?)\b")

# A clinician's name: capitalised words, nothing else. Written because matching
# "everything after the word 'provider'" harvested "Diagnosis", "Review",
# "| Legal Name: Firstname" and "for further fills if inhalers help".
NAME_RX = re.compile(
    r"^(?:Dr\.?\s+)?[A-Z][A-Za-z.'\-]*(?:\s+[A-Z][A-Za-z.'\-]*){0,3}"
    r"(?:,?\s*(?:M\.?D\.?|D\.?O\.?|N\.?P\.?|P\.?A\.?-?C|R\.?N\.?|Ph\.?D\.?))?$")


# Harvested from real documents: intake forms and portal exports put these
# immediately after a "Provider"/"Physician" label, and they read as names.
NOT_A_NAME = {
    "first name", "last name", "legal name", "full name", "middle name",
    "preferred name", "other health professional", "health professional",
    "primary care", "care team", "medical history", "chief complaint",
    "not available", "no provider", "unknown", "none", "self", "patient",
}


def _looks_like_a_name(val):
    if not (3 < len(val) < 45) or any(c in val for c in "|•❏:;/\\@"):
        return False
    if val.lower().strip(" .,") in NOT_A_NAME:
        return False
    if not NAME_RX.match(val):
        return False
    words = [w for w in re.split(r"[\s,]+", val) if w]
    if CREDENTIAL_RX.search(val):
        return True
    return len(words) >= 2          # "Diagnosis" and "Review" are not names


def extract_provider(text):
    """A clinician name from a labelled field. Returns None rather than a
    plausible-looking fragment - a wrong provider is worse than a blank one."""
    fallback = None
    for line in text.splitlines():
        for label in PROVIDER_LABELS:
            m = re.search(label + r"\s*:?\s{1,}(.+)", line, re.I)
            if not m:
                continue
            val = re.split(r"\s{3,}", m.group(1).strip())[0]
            val = re.sub(r",?\s*\d{1,2}[/-]\d{1,2}[/-]\d{2,4}.*$", "", val)
            val = val.strip(" .,:;-\t")
            if not _looks_like_a_name(val):
                continue
            if CREDENTIAL_RX.search(val):
                return val, f"labelled field ({label})"
            fallback = fallback or (val, f"labelled field ({label}), no credential")
    return fallback if fallback else (None, None)


# ============================================================
# Gate 2b - the clinician roster
# ============================================================
# The record already knows who these doctors are and where they work. Matching
# a known roster is deterministic and auditable, unlike asking a model to read a
# name off a letterhead - and clinic_name fills the facility field, which the
# letterhead heuristic almost never found.

ROSTER_CACHE = os.path.join(STATE_DIR, "clinicians.json")

# A clinician surname can also be an ordinary word
# ("standard of care", "standard precautions"). A bare surname is therefore only
# trusted when it is not a common word; otherwise the name must be anchored to
# a title or credentials.
# Fields naming someone other than the document's author.
REFERENCED_ROLE_RX = re.compile(
    r"(?:\bPCP\b|primary\s+care\s+(?:provider|physician)|"
    r"referring\s+(?:provider|physician|doctor)|"
    r"pharmac(?:y|ist)|emergency\s+contact|next\s+of\s+kin)"
    r"\s*:?[^|\n]{0,60}", re.I)

COMMON_WORDS = {
    "standard", "grant", "young", "field", "may", "chase", "cross", "king",
    "white", "brown", "green", "black", "long", "short", "best", "rich",
}


def fetch_roster(cfg, timeout=20):
    """GET the clinician roster from the server and cache it."""
    url = (cfg["server"].rstrip("/") + "/api/clinicians?user_id="
           + str(cfg["user_id"]))
    req = urllib.request.Request(
        url, headers={"Authorization": "Bearer " + cfg["api_token"]})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        data = json.loads(r.read())
    roster = data.get("clinicians") or []
    os.makedirs(STATE_DIR, exist_ok=True)
    with open(ROSTER_CACHE, "w") as f:
        json.dump(roster, f, indent=2)
    return roster


def load_roster():
    """The cached roster, or an empty list. Never fetches - matching must work
    with no network, and a stale roster is better than a failed run."""
    try:
        with open(ROSTER_CACHE) as f:
            return json.load(f)
    except (OSError, ValueError):
        return []


def _surname(name):
    parts = [w for w in re.split(r"[\s.]+", name or "") if w
             and w.lower().strip(".") not in ("dr", "mr", "ms", "mrs", "prof")]
    return parts[-1] if parts else None


def apply_roster(fields, sources, text, filename, roster):
    """Fill provider/facility from the clinician roster.

    A match on the *filename* wins outright: these files are named for the
    clinician seen, and the body of a cardiology note may well mention the
    primary care doctor - which is how Cardiology-2026-03-04.pdf came out
    attributed to Dr Example. Otherwise the roster only fills what the regexes
    left blank.
    """
    entry, why = match_clinician(text, filename, roster)
    if not entry:
        return
    authoritative = "surname in filename" in (why or "")
    if authoritative or not fields.get("provider"):
        fields["provider"] = entry["name"]
        sources["provider"] = why
    if entry.get("clinic_name") and (authoritative or not fields.get("facility")):
        fields["facility"] = entry["clinic_name"].strip()
        sources["facility"] = why


def match_clinician(text, filename, roster):
    """Best roster match for this document, or None.

    Position decides. A document's own clinician appears in the header, the
    letterhead or the signature block; a clinician merely *referenced* appears
    in the body ("follow up with Dr Example"). Matching anywhere in the document
    attributed both ER visits, the urgent care note and a nurse's telehealth
    visit to the primary care doctor, because each one says to follow up with
    him. So only the head, the signature block, and the filename count.
    """
    # Mercy's exports open with a patient banner:
    #   Name: ... | DOB: ... | MRN: ... | PCP: A. Physician, MD | ...
    # That is the patient's primary care doctor, not the author of the note, and
    # it appears on page one of every ER visit, urgent care note and telehealth
    # summary. Left in, it attributed all of them to the PCP. Referenced-role
    # fields are blanked before any matching happens.
    head = REFERENCED_ROLE_RX.sub(" ", text[:2000])
    tail = REFERENCED_ROLE_RX.sub(" ", text[-1200:])
    zones = head + "\n" + tail
    best = None
    for entry in roster:
        sur = _surname(entry.get("name"))
        if not sur or len(sur) < 3:
            continue
        e = re.escape(sur)
        score, why = 0, []
        if re.search(r"\b" + e + r"\b", filename, re.I):
            score += 6
            why.append("surname in filename")
        full = " ".join(w for w in (entry.get("name") or "").split()
                        if w.lower().strip(".") != "dr")
        if full and re.search(r"\b" + re.escape(full) + r"\b", zones, re.I):
            score += 5
            why.append("full name in header/signature")
        if re.search(r"\bDr\.?\s+" + e + r"\b", zones):
            score += 3
            why.append("'Dr <name>' in header/signature")
        if re.search(e + r"\s*,?\s*(?:M\.?D\.?|D\.?O\.?|N\.?P\.?|P\.?A\.?-?C|APRN)",
                     zones):
            score += 3
            why.append("credentials in header/signature")
        if sur.lower() not in COMMON_WORDS:
            n = len(re.findall(r"\b" + e + r"\b", head))
            if n:
                score += min(n, 2)
                why.append(f"surname in header x{n}")
        if score and (best is None or score > best[0]):
            best = (score, entry, why)
    if not best or best[0] < 5:
        return None, None
    return best[1], f"clinician roster ({', '.join(best[2])})"


ORG_RX = re.compile(
    r"(labor|patholog|clinic|hospital|health|medical|associates|diagnost|"
    r"dermatolog|rheumatolog|imaging|radiolog|cardiolog|neurolog|"
    r"center|centre|institute|group|physicians)", re.I)


NOT_A_FACILITY = re.compile(
    r"^(board\s+certified|medical\s+history|chief\s+complaint|"
    r"patient\s+information|date\s+of|page\s+\d)", re.I)


def _looks_like_an_org(line):
    if not (4 < len(line) < 70) or ":" in line or line.endswith("."):
        return False
    if NOT_A_FACILITY.match(line):
        return False
    if not line[0].isupper() or not ORG_RX.search(line):
        return False
    words = line.split()
    if len(words) < 2 or len(words) > 8:
        return False
    # A letterhead is Title Case or caps; a sentence is not.
    return sum(1 for w in words if w[:1].isupper()) >= len(words) - 1


def extract_facility(text):
    """The letterhead. On report PDFs the issuing lab or clinic is line one."""
    for line in text.splitlines()[:6]:
        line = " ".join(line.split())
        if _looks_like_an_org(line):
            return line, "letterhead (first lines)"
    for line in text.splitlines():
        m = re.search(r"performing\s+location\s*:?\s*(.+)", line, re.I)
        if m:
            val = " ".join(m.group(1).split())[:70]
            return val, "labelled field (performing location)"
    return None, None


# ============================================================
# Gate 3 - the model, for the parts that need judgement
# ============================================================

DOC_TYPES = ["clinic note", "pathology report", "lab report", "imaging report",
             "operative report", "discharge summary", "referral letter",
             "procedure note", "other"]

SPECIALTIES = ["rheumatology", "dermatology", "cardiology", "neurology",
               "primary care", "pathology", "hematology", "nephrology",
               "gastroenterology", "other"]

PROMPT = """\
You are cataloguing one clinical document for a personal medical record. Reply \
with JSON only.

Return exactly these keys:
  "title"     - a short specific name, under 70 characters. Name the study or \
visit and the site or body part if the document states one. No patient name, no \
date.
  "doc_type"  - exactly one of: {doc_types}
  "specialty" - exactly one of: {specialties}
  "summary"   - one or two sentences stating what this document found or \
concluded.

Rules that matter:
- Use the document's own wording for any finding. Do not paraphrase a result \
into a different meaning, and do not interpret, stage, or diagnose beyond what \
is written.
- If the document states a conclusion, the summary must carry that conclusion.
- Use null for any field the document does not support. Never invent a value.
- No patient name, date of birth, or record number in any field.

Document text follows.
---
{body}
---
JSON only:"""


# A label and its value are often on separate lines ("PATIENT DETAILS" above
# "FIRSTNAME A LASTNAME"), so the label match stops at the end of its own line and
# the following line is inspected separately. Using \s here instead of [ \t]
# ran the match across the newline and swallowed the label as if it were a
# name - which is how "Lastname" survived a scrub that removed "Firstname A".
# Must be a *field label*, not the word. Matching bare "patient" anywhere hit
# ordinary prose - "The patient presented with...", "Patient was located At
# home" - and took the following capitalised words as a name, learning "Video"
# and "Living Condition" as patient names and substituting them into summaries.
# So: start of line, and either a colon or an all-caps header.
PATIENT_LABEL_RX = re.compile(
    r"^[ \t]*(?:patient(?:[ \t]+(?:name|details|information))?[ \t]*:"
    r"|PATIENT[ \t]+(?:DETAILS|NAME|INFORMATION)[ \t]*$)", re.I)
NAME_TOKENS_RX = re.compile(
    r"([A-Z][A-Za-z.'\-]{1,}(?:(?:,[ \t]*|[ \t]+)[A-Z][A-Za-z.'\-]*){1,3})")

NAME_STOPWORDS = {
    "name", "names", "patient", "details", "detail", "information", "info",
    "date", "birth", "sex", "male", "female", "the", "and", "for", "ids", "id",
    "record", "number", "account", "dob", "age", "phone", "address", "mrn",
    "summary", "visit", "results", "report", "lab", "labs", "test", "tests",
    "case", "unit", "location", "provider", "client", "deliver", "consulting",
}


def _name_parts(raw):
    parts = [w.strip(" .,") for w in re.split(r"[,\s]+", raw)]
    return [w for w in parts if len(w) > 2 and w.lower() not in NAME_STOPWORDS]


def patient_names(text, extra=()):
    """Name fragments belonging to the patient, for scrubbing model output.

    `extra` comes from config.json ("patient_names"). That list is the reliable
    half: the patient is the same person in every document, whereas per-document
    detection depends on however this particular portal lays out its header.
    Detection stays as a backstop for documents naming someone the list misses.

    The prompt already forbids putting a patient name in a field; qwen did it
    anyway in 2 of 28 documents. An instruction is not a control.
    """
    names = set()
    for n in extra or ():
        names.update(_name_parts(n))
        names.add(n.strip())

    lines = text[:6000].splitlines()
    for i, line in enumerate(lines):
        m = PATIENT_LABEL_RX.search(line)
        if not m:
            continue
        # Stop at the column break, or the capture runs on into the next field
        # ("Patient Name: Lastname, Firstname A     Case #: X-00-0000000" taught it
        # that "Case" was part of the name).
        rest = re.split(r"\s{3,}", line[m.end():].strip())[0]
        cand = NAME_TOKENS_RX.match(rest)
        if not cand:                       # value wrapped to the following line
            for probe in lines[i + 1:i + 3]:
                if probe.strip():
                    cand = NAME_TOKENS_RX.match(
                        re.split(r"\s{3,}", probe.strip())[0])
                    break
        if cand:
            parts = _name_parts(cand.group(1))
            if parts:
                names.update(parts)
                names.add(" ".join(parts))
    return {n for n in names if n and n.lower() not in NAME_STOPWORDS}


def scrub_identifiers(fields, text, extra=()):
    """Strip patient identifiers out of the model's free-text fields.

    A title drops the name outright - "Lab Results for Firstname A Lastname"
    becomes "Lab Results". A summary keeps its grammar by substituting "the
    patient", since the sentence is usually about them. Middle initials adjacent
    to a removed name go too, or the field keeps a stray capital letter.

    Returns the list of fields that were changed.
    """
    names = sorted(patient_names(text, extra), key=len, reverse=True)
    if not names:
        return []
    alts = "|".join(re.escape(n) for n in names)
    # One match must swallow the whole name, however it is written: "Lastname,
    # Firstname A" is three tokens, and matching them separately yields "the
    # patient, the patient". After the first part, keep consuming further name
    # parts and bare initials.
    name_rx = re.compile(
        r"\b(?:" + alts + r")\b(?:[\s,]+(?:(?:" + alts + r")\b|[A-Z]\.?(?![a-z])))*",
        re.I)

    changed = []
    for key in ("title", "summary"):
        val = fields.get(key)
        if not val or not name_rx.search(val):
            continue
        if key == "title":
            out = name_rx.sub("", val)
            out = re.sub(r"\s*\b(?:for|of|to|by)\s*$", "", out.strip(), flags=re.I)
        else:
            out = name_rx.sub("the patient", val)
            out = re.sub(r"(?:\bthe patient\b[\s,]*){2,}", "the patient ", out,
                         flags=re.I)
        out = re.sub(r"\s{2,}", " ", out).strip(" -,:;")
        if out:
            out = out[0].upper() + out[1:]
        fields[key] = out or None
        changed.append(key)
    return changed


def http_json(path, payload, timeout=900):
    req = urllib.request.Request(
        HOST + path, data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


class Working:
    """Spinner for the slow call. Prefill dominates; expect 30-90s a document."""

    def __init__(self, label):
        self.label, self.stop, self.t0 = label, threading.Event(), time.monotonic()

    def __enter__(self):
        if sys.stderr.isatty():
            threading.Thread(target=self._spin, daemon=True).start()
        return self

    def _spin(self):
        frames = "|/-\\"
        i = 0
        while not self.stop.is_set():
            sys.stderr.write(
                f"\r  {frames[i % 4]} {self.label} {time.monotonic() - self.t0:4.0f}s")
            sys.stderr.flush()
            i += 1
            self.stop.wait(0.25)

    def __exit__(self, *exc):
        self.stop.set()
        if sys.stderr.isatty():
            sys.stderr.write("\r" + " " * 60 + "\r")
            sys.stderr.flush()


def describe(text, model):
    """Ask the model for title / doc_type / specialty / summary."""
    body = text[:MODEL_CHARS]
    if len(text) > MODEL_CHARS:
        body += "\n[document truncated for length]"
    payload = {
        "model": model,
        "prompt": PROMPT.format(doc_types=", ".join(DOC_TYPES),
                                specialties=", ".join(SPECIALTIES), body=body),
        "stream": False,
        "think": THINK,
        "format": "json",
        "options": {"temperature": 0, "seed": 42,
                    "num_ctx": NUM_CTX, "num_predict": NUM_PREDICT},
    }
    with Working("qwen is reading the document"):
        r = http_json("/api/generate", payload)
    raw = (r.get("response") or "").strip()
    if "</think>" in raw:                        # belt and braces alongside think=False
        raw = raw.split("</think>", 1)[1].strip()
    try:
        out = json.loads(raw)
    except ValueError:
        m = re.search(r"\{.*\}", raw, re.S)
        if not m:
            return None, f"model returned no JSON: {raw[:160]}"
        try:
            out = json.loads(m.group(0))
        except ValueError as e:
            return None, f"model JSON did not parse: {e}"

    clean = {}
    for k in ("title", "doc_type", "specialty", "summary"):
        v = out.get(k)
        clean[k] = v.strip() if isinstance(v, str) and v.strip() else None
    if clean["doc_type"] and clean["doc_type"].lower() not in DOC_TYPES:
        clean["doc_type"] = "other"
    if clean["specialty"] and clean["specialty"].lower() not in SPECIALTIES:
        clean["specialty"] = "other"
    return clean, None


# ============================================================
# Plumbing
# ============================================================

def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def extract_text(path):
    """Layout-preserving text. -layout is not cosmetic here: without it the
    header is linearised and 'Provider:' lands four lines from its value."""
    try:
        out = subprocess.run(["pdftotext", "-q", "-layout", path, "-"],
                             capture_output=True, timeout=60)
        text = out.stdout.decode("utf-8", "replace").strip()
        if text:
            return text
    except (OSError, subprocess.SubprocessError):
        pass
    return None


def load_manifest():
    if os.path.exists(MANIFEST):
        with open(MANIFEST) as f:
            return json.load(f)
    return {}


def save_manifest(m):
    os.makedirs(STATE_DIR, exist_ok=True)
    tmp = MANIFEST + ".tmp"
    with open(tmp, "w") as f:
        json.dump(m, f, indent=2, sort_keys=True)
    os.replace(tmp, MANIFEST)


def now():
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def triage_one(path, model, dry_run):
    """Run one document through the gates. Returns the proposal dict."""
    name = os.path.basename(path)
    digest = sha256_file(path)
    prop = {
        "sha256": digest, "source_file": name,
        "source_path": os.path.abspath(path),
        "bytes": os.path.getsize(path), "triaged_at": now(),
        "status": "pending", "fields": {}, "field_sources": {},
    }

    text = extract_text(path)
    if not text:
        prop["status"] = "needs_ocr"
        prop["note"] = "No text layer. Scanned PDF - needs OCR before it can be read."
        return prop

    verdict, detail = classify(text)
    prop["classification"] = dict(detail, verdict=verdict)
    if verdict in ("not_clinical", "too_short"):
        prop["status"] = verdict
        prop["note"] = detail.get("reason")
        return prop

    for key, fn in (("date", lambda t: extract_date(t, name)),
                    ("provider", extract_provider),
                    ("facility", extract_facility)):
        value, source = fn(text)
        prop["fields"][key] = value
        prop["field_sources"][key] = source

    apply_roster(prop["fields"], prop["field_sources"], text, name, ROSTER)

    if dry_run:
        prop["status"] = "extracted"
        prop["note"] = "--dry-run: model not called, no description proposed."
        return prop

    described, err = describe(text, model)
    if err:
        prop["status"] = "describe_failed"
        prop["note"] = err
        return prop
    prop["fields"].update(described)
    for k in described:
        prop["field_sources"][k] = f"model ({model})"
    for k in scrub_identifiers(prop["fields"], text, KNOWN_NAMES):
        prop["field_sources"][k] = f"model ({model}), patient name removed"
    prop["status"] = "described" if verdict == "clinical" else "described_ambiguous"
    return prop


def write_proposal(prop):
    os.makedirs(QUEUE_DIR, exist_ok=True)
    path = os.path.join(QUEUE_DIR, prop["sha256"][:16] + ".json")
    with open(path, "w") as f:
        json.dump(prop, f, indent=2)
    return path


LOCK = os.path.join(STATE_DIR, "triage.lock")


class Busy(Exception):
    pass


def acquire_lock():
    """One triage at a time. Two concurrent runs share a manifest and a queue
    directory, so the second silently overwrites the first's work - including
    replacing finished descriptions with un-described ones."""
    os.makedirs(STATE_DIR, exist_ok=True)
    if os.path.exists(LOCK):
        try:
            with open(LOCK) as f:
                pid = int(f.read().strip())
        except (ValueError, OSError):
            pid = None
        if pid:
            try:
                os.kill(pid, 0)
            except OSError:
                pass                      # stale lock, the process is gone
            else:
                raise Busy(f"another triage is running (pid {pid}). "
                           f"Wait for it, or remove {LOCK} if you are sure "
                           f"it is dead.")
    with open(LOCK, "w") as f:
        f.write(str(os.getpid()))


def release_lock():
    try:
        os.remove(LOCK)
    except OSError:
        pass


def reextract():
    """Recompute date / provider / facility for every queued proposal.

    The model's fields are expensive and are left exactly as they are; only the
    regex-derived ones are refreshed. Use after changing an extractor, instead
    of paying for another full describe run.
    """
    files = sorted(f for f in os.listdir(QUEUE_DIR)
                   if f.endswith(".json")) if os.path.isdir(QUEUE_DIR) else []
    if not files:
        print("Queue is empty.")
        return
    changed = 0
    for fn in files:
        path = os.path.join(QUEUE_DIR, fn)
        with open(path) as f:
            prop = json.load(f)
        src = prop.get("source_path")
        if not src or not os.path.exists(src):
            print(f"  ?  {prop['source_file']}: source PDF missing, skipped")
            continue
        text = extract_text(src)
        if not text:
            continue
        changed_names = False
        before = {k: prop["fields"].get(k) for k in ("date", "provider", "facility")}
        for key, fn_ in (("date", lambda t: extract_date(t, prop["source_file"])),
                         ("provider", extract_provider),
                         ("facility", extract_facility)):
            value, source = fn_(text)
            prop["fields"][key] = value
            prop["field_sources"][key] = source
        apply_roster(prop["fields"], prop["field_sources"], text,
                     prop["source_file"], ROSTER)
        for k in scrub_identifiers(prop["fields"], text, KNOWN_NAMES):
            src = prop["field_sources"].get(k) or "model"
            if "removed" not in src:
                prop["field_sources"][k] = src + ", patient name removed"
            changed_names = True
        after = {k: prop["fields"].get(k) for k in ("date", "provider", "facility")}
        if before != after or changed_names:
            changed += 1
            print(f"\n  {prop['source_file']}")
            for k in ("date", "provider", "facility"):
                if before[k] != after[k]:
                    print(f"      {k:<9} {before[k]!r}  ->  {after[k]!r}")
        with open(path, "w") as f:
            json.dump(prop, f, indent=2)
    print(f"\n{changed} of {len(files)} proposals changed.")


# ============================================================
# Output
# ============================================================

STATUS_MARK = {
    "described": "+", "described_ambiguous": "?", "extracted": "+",
    "not_clinical": "-", "too_short": "-", "needs_ocr": "!",
    "describe_failed": "!",
}


def show(prop, verbose):
    mark = STATUS_MARK.get(prop["status"], " ")
    print(f"\n  {mark} {prop['source_file']}  [{prop['status']}]")
    c = prop.get("classification")
    if c:
        print(f"      {c['verdict']}: {c.get('reason','')}")
        if verbose:
            a = "  ".join(f"{k}={v}" for k, v in c["anchors"].items())
            v = "  ".join(f"{k}={n}" for k, n in c["vetoes"].items() if n)
            print(f"          anchors  {a}   ({c['chars']} chars)")
            if v:
                print(f"          vetoes   {v}")
    if prop.get("note"):
        print(f"      note: {prop['note']}")
    for k in ("date", "title", "doc_type", "specialty", "provider", "facility",
              "summary"):
        if k in prop["fields"]:
            v = prop["fields"][k]
            src = prop["field_sources"].get(k) or "not found"
            shown = v if v is not None else "--"
            if isinstance(shown, str) and len(shown) > 66:
                shown = shown[:63] + "..."
            print(f"      {k:<10} {shown}")
            if verbose or v is None:
                print(f"      {'':<10}   via {src}")


def report():
    files = sorted(f for f in os.listdir(QUEUE_DIR) if f.endswith(".json")) \
        if os.path.isdir(QUEUE_DIR) else []
    if not files:
        print("Queue is empty.")
        return
    print(f"{len(files)} proposal(s) in {QUEUE_DIR}\n")
    for fn in files:
        with open(os.path.join(QUEUE_DIR, fn)) as f:
            p = json.load(f)
        title = p["fields"].get("title") or p["source_file"]
        date = p["fields"].get("date") or "??????????"
        print(f"  {STATUS_MARK.get(p['status'],' ')} {date}  {title[:56]:<56} "
              f"{p['status']}")


def main():
    ap = argparse.ArgumentParser(
        description="Triage clinical PDFs out of the Taildrop inbox.")
    ap.add_argument("--inbox", default=DEFAULT_INBOX,
                    help=f"directory to scan (default {DEFAULT_INBOX})")
    ap.add_argument("--model", default=MODEL, help=f"Ollama model (default {MODEL})")
    ap.add_argument("--dry-run", action="store_true",
                    help="classify and extract, but never call the model")
    ap.add_argument("--force", action="store_true",
                    help="re-triage documents already in the manifest")
    ap.add_argument("--limit", type=int, help="stop after N new documents")
    ap.add_argument("--report", action="store_true", help="list the queue and exit")
    ap.add_argument("--refresh-roster", action="store_true",
                    help="re-fetch the clinician roster from the server first")
    ap.add_argument("--reextract", action="store_true",
                    help="recompute date/provider/facility for queued proposals, "
                         "leaving the model's fields alone")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="show classifier evidence and every field's provenance")
    a = ap.parse_args()

    if a.report:
        report()
        return

    global ROSTER
    if a.refresh_roster:
        try:
            with open(os.path.join(HERE, "config.json")) as f:
                cfg = json.load(f)
            ROSTER = fetch_roster(cfg)
            print(f"roster: fetched {len(ROSTER)} clinicians")
        except (OSError, ValueError, urllib.error.URLError) as e:
            sys.exit(f"Could not fetch the roster: {e}")
    else:
        ROSTER = load_roster()
        if ROSTER:
            print(f"roster: {len(ROSTER)} clinicians (cached; "
                  f"--refresh-roster to update)")

    try:
        acquire_lock()
    except Busy as e:
        sys.exit(str(e))

    try:
        _run(a)
    finally:
        release_lock()


def _run(a):
    if a.reextract:
        reextract()
        return

    if not os.path.isdir(a.inbox):
        sys.exit(f"No such directory: {a.inbox}")

    if not a.dry_run:
        try:
            urllib.request.urlopen(HOST + "/api/tags", timeout=10).read()
        except (urllib.error.URLError, OSError) as e:
            sys.exit(f"Cannot reach Ollama at {HOST} ({e}).\n"
                     f"Start it with:  ollama serve\n"
                     f"Or classify without a model:  {sys.argv[0]} --dry-run")

    pdfs = sorted(os.path.join(a.inbox, f) for f in os.listdir(a.inbox)
                  if f.lower().endswith(".pdf"))
    if not pdfs:
        print(f"No PDFs in {a.inbox}")
        return

    manifest = load_manifest()
    print(f"clinic-triage  ·  {len(pdfs)} PDF(s) in {a.inbox}"
          f"{'  ·  dry run' if a.dry_run else '  ·  model ' + a.model}")

    seen = new = 0
    for path in pdfs:
        digest = sha256_file(path)
        if digest in manifest and not a.force:
            seen += 1
            continue
        if a.limit and new >= a.limit:
            break
        prop = triage_one(path, a.model, a.dry_run)
        show(prop, a.verbose)
        if prop["status"] not in ("not_clinical", "too_short"):
            write_proposal(prop)
        manifest[digest] = {
            "source_file": prop["source_file"], "first_seen": now(),
            "status": prop["status"],
        }
        new += 1

    save_manifest(manifest)
    print(f"\n{new} triaged, {seen} already in the manifest.")
    if new and not a.dry_run:
        print(f"Proposals in {QUEUE_DIR} — read them before stage 3 posts anything.")


if __name__ == "__main__":
    main()
